### ISSUE TITLE
Error: spawn emcc ENOENT

### ISSUE THREAD

**Issue by mensta** [mezum/emcc-loader#4]
i got err when i built projects

```
ERROR in ./src/wasm.clist
Module build failed (from ./node_modules/emcc-loader/lib/index.js):
Error: spawn emcc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
 @ ./src/index.js 6:0-32 7:0-4
```

I added emscripten path to envpath and emcc command works anyhwhere.
But I cant build c in emcc-loader

OS: Windows10

**Comment by mezum** [comment]
mensta-san, thanks for your reporting of error and using this loader.
the problem is caused probably by [the function `utility.execute(file, string, options)`](https://github.com/mezum/emcc-loader/blob/master/src/utility.ts#L66) that not spawns with `cmd` on windows so it must be fixed like [this StackOverflow answer](https://stackoverflow.com/a/37487465).
i'll maybe fix it on the weekend if i forgot.

**Comment by mensta** [comment]
thanks for ur reply!
now, I modified a module file and it works good!
btw you may need to remove ENVIRONMENT option because i got err like
 `Module.ENVIRONMENT has been deprecated.`

anyway, thanks for ur help and amazing work!!
